### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by JeremySkinner** [dahlbyk/posh-sshell#6]
# 0.1 

- [x] Parity with posh-git 0.8.
- [x] Add-PoshSshellToProfile function
- [x] Tests
- [x] Windows CI build
- [x] Linux CI build

# 0.2 

- [x] Port SSH Config file parser
- [x] Refactor Config file parser
- [x] Add functions for manipulating config file
- [x] Add function for displying and connecting to saved connections

# 0.3 
- [ ] Tab expansion
